[program:reverb]
command=php /var/www/html/artisan reverb:start
directory=/var/www/html
autostart=true
autorestart=true
stderr_logfile=/var/log/reverb.err.log
stdout_logfile=/var/log/reverb.out.log
user=www-data
